# Вычисление логических функций средствами однослойных искусственных нейронных сетей

В качестве примера построим и обучим искусственную нейронную сеть (ИНС) вычислению конъюнкции.

Сначала подгрузим библиотеки с линейной моделью слоев Sequential, со слоями Dense

In [32]:
from keras.models import Sequential
from keras.layers import Dense, Activation


Создадим модель ИНС и добавим в нее один слой с одним нейроном (units = 1) и двумя входами (input_dim = 2)

In [71]:
from keras import activations
model = Sequential()
model.add(Dense(units = 1, input_dim = 2, activation='sigmoid'))


Скомпилируем, получившуюся ИНС

In [99]:
model.compile(optimizer='sgd', loss='mse', metrics=['binary_accuracy'])

Создадим обучающий набор X и вектор значений целевой функции (конъюнкции)

In [73]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [96]:
y = np.array([0, 0, 0, 1])
y

array([0, 0, 0, 1])

Обучим ИНС

In [100]:
model.fit(X, y, epochs=5)

Epoch 1/5
1/1 [==============================] - 0s 426ms/step - loss: 0.2663 - binary_accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 0.2662 - binary_accuracy: 0.5000
Epoch 3/5
1/1 [==============================] - 0s 9ms/step - loss: 0.2662 - binary_accuracy: 0.5000
Epoch 4/5
1/1 [==============================] - 0s 12ms/step - loss: 0.2661 - binary_accuracy: 0.5000
Epoch 5/5
1/1 [==============================] - 0s 10ms/step - loss: 0.2660 - binary_accuracy: 0.5000


Протестируем ИНС

In [101]:
model.predict(X)

array([[0.46434826],
       [0.63457644],
       [0.22922757],
       [0.37333685]], dtype=float32)

1. Обучить ИНС для вычисления дизъюнкции

2. Обучить ИНС для вычисления импликации

3. Обучить ИНС для вычисления сложения по модулю два