# Подбор параметров для вычисления логических функций средствами однослойных искусственных нейронных сетей

В качестве примера построим и обучим искусственную нейронную сеть (ИНС) вычислению конъюнкции.

Сначала подгрузим библиотеки с линейной моделью слоев Sequential, со слоями Dense

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation


Создадим модель ИНС и добавим в нее один слой с одним нейроном (units = 1) и двумя входами (input_dim = 2)

In [2]:
from keras import activations
model = Sequential()
model.add(Dense(units = 1, input_dim = 2, activation='sigmoid'))


Скомпилируем, получившуюся ИНС

In [3]:
model.compile(optimizer='sgd', loss='mse', metrics=['binary_accuracy'])

Создадим обучающий набор X и вектор значений целевой функции (конъюнкции)

In [4]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
y = np.array([0, 0, 0, 1])
y

array([0, 0, 0, 1])

Обучим ИНС

In [6]:
model.fit(X, y, epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 557ms/step - loss: 0.2758 - binary_accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 0.2757 - binary_accuracy: 0.5000
Epoch 3/5
1/1 [==============================] - 0s 8ms/step - loss: 0.2756 - binary_accuracy: 0.5000
Epoch 4/5
1/1 [==============================] - 0s 8ms/step - loss: 0.2755 - binary_accuracy: 0.5000
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 0.2754 - binary_accuracy: 0.5000


Протестируем ИНС

In [7]:
model.predict(X)

array([[0.4988046 ],
       [0.70385486],
       [0.26753503],
       [0.46588784]], dtype=float32)

Посмотрим как влияет выбор функции активации на результат классификации

In [11]:
f_act = ['elu', 'softmax', 'selu', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'exponential', 'linear']
for f in f_act:
  model = Sequential()
  model.add(Dense(units = 1, input_dim = 2, activation=f))
  model.compile(optimizer='sgd', loss='mse', metrics=['binary_accuracy'])
  model.fit(X, y, epochs=10)
  yp = model.predict(X)
  print(f, yp)

Epoch 1/10
1/1 [==============================] - 0s 334ms/step - loss: 0.5772 - binary_accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5731 - binary_accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 0.5690 - binary_accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5649 - binary_accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5608 - binary_accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 0.5567 - binary_accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 0.5527 - binary_accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 0.5486 - binary_accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 0.5446 - binary_accuracy: 0.5000
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 

1. Проверьте влияние на результат еще и таких параметров, как optimizer, loss, metrics

2. Скомбинируйте изменение нескольких параметров: activation, optimizer, loss, metrics, -- для проверки их комплексного влияния на результат