# Вычисление логических функций средствами однослойных искусственных нейронных сетей

В качестве примера построим и обучим искусственную нейронную сеть (ИНС) вычислению конъюнкции.

Сначала подгрузим библиотеки с линейной моделью слоев Sequential, со слоями Dense

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD


Создадим модель ИНС и добавим в нее один слой с одним нейроном (units = 1) и двумя входами (input_dim = 2)

In [2]:
from keras import activations
model = Sequential()
model.add(Dense(units = 1, input_dim = 2, activation='sigmoid'))


Скомпилируем, получившуюся ИНС

In [3]:
optimizer = keras.optimizers.SGD(learning_rate = 0.6)

model.compile(optimizer, loss='mse', metrics=['binary_accuracy'])

Создадим обучающий набор X и вектор значений целевой функции (конъюнкции)

In [4]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
y = np.array([0, 0, 0, 1])
y

array([0, 0, 0, 1])

Обучим ИНС

In [6]:
model.fit(X, y, epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 514ms/step - loss: 0.2744 - binary_accuracy: 0.5000
Epoch 2/5
1/1 [==============================] - 0s 15ms/step - loss: 0.2555 - binary_accuracy: 0.7500
Epoch 3/5
1/1 [==============================] - 0s 13ms/step - loss: 0.2394 - binary_accuracy: 0.7500
Epoch 4/5
1/1 [==============================] - 0s 14ms/step - loss: 0.2259 - binary_accuracy: 0.7500
Epoch 5/5
1/1 [==============================] - 0s 12ms/step - loss: 0.2147 - binary_accuracy: 0.7500


Протестируем ИНС

In [7]:
model.predict(X)

1/1 [==============================] - 0s 82ms/step


array([[0.3908316 ],
       [0.38810697],
       [0.58954555],
       [0.58677   ]], dtype=float32)

1. Обучить ИНС для вычисления дизъюнкции

In [8]:
# Генерируем обучающие данные для дизъюнкции

Y = np.array([[0], [1], [1], [1]])


# Компилируем модель
model.compile(optimizer, loss='binary_crossentropy', metrics=['accuracy'])



# Обучаем модель
model.fit(X, Y, epochs=100)

# Проверяем предсказания
predictions = model.predict(X)
print(predictions)


Epoch 1/100
1/1 [==============================] - 0s 375ms/step - loss: 0.6259 - accuracy: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 0.5316 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 0.4729 - accuracy: 1.0000
Epoch 4/100
1/1 [==============================] - 0s 10ms/step - loss: 0.4342 - accuracy: 1.0000
Epoch 5/100
1/1 [==============================] - 0s 12ms/step - loss: 0.4073 - accuracy: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 13ms/step - loss: 0.3876 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 10ms/step - loss: 0.3725 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.3603 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 9ms/step - loss: 0.3502 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.3415 - accuracy: 0.7500
Epoch 11/100
1/1 [=

2. Обучить ИНС для вычисления импликации

In [9]:
# Генерируем обучающие данные для импликации
X_train_impl = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train_impl = np.array([[1], [1], [0], [1]])  # Импликация A -> B

# Создаем модель для импликации
model_impl = Sequential([
    Dense(32, input_shape=(2,)),
    Activation('relu'),
    Dense(1),
    Activation('sigmoid')
])

# Компилируем модель для импликации
model_impl.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Обучаем модель для импликации
model_impl.fit(X_train_impl, y_train_impl, epochs=100)

# Проверяем предсказания для импликации
predictions_impl = model_impl.predict(X_train_impl)
print(predictions_impl)

Epoch 1/100
1/1 [==============================] - 1s 675ms/step - loss: 0.7003 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6972 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6941 - accuracy: 0.7500
Epoch 4/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6911 - accuracy: 0.7500
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6881 - accuracy: 0.7500
Epoch 6/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6851 - accuracy: 0.7500
Epoch 7/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6821 - accuracy: 0.7500
Epoch 8/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6793 - accuracy: 0.7500
Epoch 9/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6765 - accuracy: 0.7500
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 0.6737 - accuracy: 0.7500
Epoch 11/100
1/1 [

3. Обучить ИНС для вычисления сложения по модулю два

In [10]:
# Генерируем обучающие данные для сложения по модулю два
X_train_add = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_train_add = np.array([[0], [1], [1], [0]])  # Сложение по модулю два

# Создаем модель для сложения по модулю два
model_add = Sequential([
    Dense(32, input_shape=(2,)),
    Activation('relu'),
    Dense(1),
    Activation('sigmoid')
])

# Компилируем модель для сложения по модулю два
model_add.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Обучаем модель для сложения по модулю два
model_add.fit(X_train_add, y_train_add, epochs=100)

# Проверяем предсказания для сложения по модулю два
predictions_add = model_add.predict(X_train_add)
print(predictions_add)


Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.6668 - accuracy: 0.7500
Epoch 2/100
1/1 [==============================] - 0s 20ms/step - loss: 0.6659 - accuracy: 0.7500
Epoch 3/100
1/1 [==============================] - 0s 17ms/step - loss: 0.6650 - accuracy: 1.0000
Epoch 4/100
1/1 [==============================] - 0s 19ms/step - loss: 0.6641 - accuracy: 1.0000
Epoch 5/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6632 - accuracy: 1.0000
Epoch 6/100
1/1 [==============================] - 0s 14ms/step - loss: 0.6623 - accuracy: 1.0000
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6614 - accuracy: 1.0000
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6605 - accuracy: 1.0000
Epoch 9/100
1/1 [==============================] - 0s 10ms/step - loss: 0.6596 - accuracy: 1.0000
Epoch 10/100
1/1 [==============================] - 0s 11ms/step - loss: 0.6588 - accuracy: 1.0000
Epoch 11/100
1/1 [===