# Подбор параметров для вычисления логических функций средствами однослойных искусственных нейронных сетей

В качестве примера построим и обучим искусственную нейронную сеть (ИНС) вычислению конъюнкции.

Сначала подгрузим библиотеки с линейной моделью слоев Sequential, со слоями Dense

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation


Создадим модель ИНС и добавим в нее один слой с одним нейроном (units = 1) и двумя входами (input_dim = 2)

In [2]:
from keras import activations
model = Sequential()
model.add(Dense(units = 1, input_dim = 2, activation='sigmoid'))


Скомпилируем, получившуюся ИНС

In [3]:
model.compile(optimizer='sgd', loss='mse', metrics=['binary_accuracy'])

Создадим обучающий набор X и вектор значений целевой функции (конъюнкции)

In [4]:
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [5]:
y = np.array([0, 0, 0, 1])
y

array([0, 0, 0, 1])

Обучим ИНС

In [6]:
model.fit(X, y, epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 501ms/step - loss: 0.2871 - binary_accuracy: 0.7500
Epoch 2/5
1/1 [==============================] - 0s 11ms/step - loss: 0.2870 - binary_accuracy: 0.7500
Epoch 3/5
1/1 [==============================] - 0s 10ms/step - loss: 0.2869 - binary_accuracy: 0.7500
Epoch 4/5
1/1 [==============================] - 0s 10ms/step - loss: 0.2868 - binary_accuracy: 0.7500
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 0.2867 - binary_accuracy: 0.7500


Протестируем ИНС

In [7]:
model.predict(X)

1/1 [==============================] - 0s 80ms/step


array([[0.49885863],
       [0.7995964 ],
       [0.23234206],
       [0.5481518 ]], dtype=float32)

Посмотрим как влияет выбор функции активации на результат классификации

In [8]:
f_act = ['elu', 'softmax', 'selu', 'softplus', 'softsign', 'relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'exponential', 'linear']
for f in f_act:
  model = Sequential()
  model.add(Dense(units = 1, input_dim = 2, activation=f))
  model.compile(optimizer='sgd', loss='mse', metrics=['binary_accuracy'])
  model.fit(X, y, epochs=10)
  yp = model.predict(X)
  print(f, yp)

Epoch 1/10
1/1 [==============================] - 0s 325ms/step - loss: 0.7185 - binary_accuracy: 0.7500
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.7124 - binary_accuracy: 0.7500
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 0.7064 - binary_accuracy: 0.7500
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 0.7003 - binary_accuracy: 0.7500
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 0.6942 - binary_accuracy: 0.7500
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6880 - binary_accuracy: 0.7500
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.6819 - binary_accuracy: 0.7500
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6758 - binary_accuracy: 0.7500
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 0.6696 - binary_accuracy: 0.7500
Epoch 10/10
1/1 [==============================] - 0s 47ms/step
e

1/1 [==============================] - 0s 45ms/step
softplus [[0.676436 ]
 [0.3983009]
 [0.7413023]
 [0.4421167]]
Epoch 1/10
1/1 [==============================] - 0s 318ms/step - loss: 0.4970 - binary_accuracy: 0.7500
Epoch 2/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4926 - binary_accuracy: 0.7500
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4881 - binary_accuracy: 0.7500
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4835 - binary_accuracy: 0.7500
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4788 - binary_accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4739 - binary_accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 0.4690 - binary_accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 0.4639 - binary_accuracy: 0.5000
Epoch 9/10
1/1 [==============================] - 0s 9

1/1 [==============================] - 0s 53ms/step
softsign [[ 0.03776538]
 [-0.5324254 ]
 [ 0.51143473]
 [-0.1159319 ]]
Epoch 1/10
1/1 [==============================] - 0s 322ms/step - loss: 0.3750 - binary_accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 0.3725 - binary_accuracy: 0.5000
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 0.3701 - binary_accuracy: 0.5000
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 0.3677 - binary_accuracy: 0.5000
Epoch 5/10
1/1 [==============================] - 0s 15ms/step - loss: 0.3654 - binary_accuracy: 0.5000
Epoch 6/10
1/1 [==============================] - 0s 13ms/step - loss: 0.3631 - binary_accuracy: 0.5000
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 0.3608 - binary_accuracy: 0.5000
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 0.3586 - binary_accuracy: 0.5000
Epoch 9/10
1/1 [=============================

1. Проверьте влияние на результат еще и таких параметров, как optimizer, loss, metrics

In [9]:
optimizers = ['sgd', 'rmsprop', 'adam', 'adagrad']
losses = ['mean_squared_error', 'binary_crossentropy']
metrics = ['accuracy', 'binary_accuracy']

for optimizer in optimizers:
    for loss in losses:
        for metric in metrics:
            model = Sequential()
            model.add(Dense(units=1, input_dim=2, activation='sigmoid'))
            model.compile(optimizer=optimizer, loss=loss, metrics=[metric])
            model.fit(X, y, epochs=10, verbose=0)
            score = model.evaluate(X, y)
            print("Optimizer:", optimizer, "- Loss:", loss, "- Metric:", metric)
            print("Score:", score)


1/1 [==============================] - 0s 172ms/step - loss: 0.2622 - accuracy: 0.7500
Optimizer: sgd - Loss: mean_squared_error - Metric: accuracy
Score: [0.2622445225715637, 0.75]
1/1 [==============================] - 0s 434ms/step - loss: 0.2614 - binary_accuracy: 0.7500
Optimizer: sgd - Loss: mean_squared_error - Metric: binary_accuracy
Score: [0.2614448070526123, 0.75]
1/1 [==============================] - 0s 122ms/step - loss: 0.7255 - accuracy: 0.7500
Optimizer: sgd - Loss: binary_crossentropy - Metric: accuracy
Score: [0.7254806160926819, 0.75]
1/1 [==============================] - 0s 133ms/step - loss: 0.7561 - binary_accuracy: 0.7500
Optimizer: sgd - Loss: binary_crossentropy - Metric: binary_accuracy
Score: [0.7560715079307556, 0.75]


1/1 [==============================] - 0s 121ms/step - loss: 0.2720 - accuracy: 0.5000
Optimizer: rmsprop - Loss: mean_squared_error - Metric: accuracy
Score: [0.27198490500450134, 0.5]


1/1 [==============================] - 0s 109ms/step - loss: 0.3008 - binary_accuracy: 0.5000
Optimizer: rmsprop - Loss: mean_squared_error - Metric: binary_accuracy
Score: [0.30078092217445374, 0.5]
1/1 [==============================] - 0s 167ms/step - loss: 0.7196 - accuracy: 0.7500
Optimizer: rmsprop - Loss: binary_crossentropy - Metric: accuracy
Score: [0.7195749282836914, 0.75]
1/1 [==============================] - 0s 202ms/step - loss: 0.7313 - binary_accuracy: 0.7500
Optimizer: rmsprop - Loss: binary_crossentropy - Metric: binary_accuracy
Score: [0.7313271164894104, 0.75]
1/1 [==============================] - 0s 123ms/step - loss: 0.2701 - accuracy: 0.5000
Optimizer: adam - Loss: mean_squared_error - Metric: accuracy
Score: [0.27014732360839844, 0.5]
1/1 [==============================] - 0s 126ms/step - loss: 0.3172 - binary_accuracy: 0.5000
Optimizer: adam - Loss: mean_squared_error - Metric: binary_accuracy
Score: [0.3172495365142822, 0.5]
1/1 [============================

2. Скомбинируйте изменение нескольких параметров: activation, optimizer, loss, metrics, -- для проверки их комплексного влияния на результат

In [13]:
for f in f_act:
    for optimizer in optimizers:
        for loss in losses:
            for metric in metrics:
                model = Sequential()
                model.add(Dense(units=1, input_dim=2, activation=f))
                model.compile(optimizer=optimizer, loss=loss, metrics=[metric])
                model.fit(X, y, epochs=10, verbose=0)
                score = model.evaluate(X, y)
                print("Activation:", f, "- Optimizer:", optimizer, "- Loss:", loss, "- Metric:", metric)
                print("Score:", score)

1/1 [==============================] - 0s 157ms/step - loss: 0.3450 - accuracy: 0.7500
Activation: elu - Optimizer: sgd - Loss: mean_squared_error - Metric: accuracy
Score: [0.34501177072525024, 0.75]
1/1 [==============================] - 0s 193ms/step - loss: 0.5885 - binary_accuracy: 0.5000
Activation: elu - Optimizer: sgd - Loss: mean_squared_error - Metric: binary_accuracy
Score: [0.5885244607925415, 0.5]
1/1 [==============================] - 0s 124ms/step - loss: 3.9065 - accuracy: 0.7500
Activation: elu - Optimizer: sgd - Loss: binary_crossentropy - Metric: accuracy
Score: [3.9064688682556152, 0.75]
1/1 [==============================] - 0s 133ms/step - loss: 3.8844 - binary_accuracy: 0.7500
Activation: elu - Optimizer: sgd - Loss: binary_crossentropy - Metric: binary_accuracy
Score: [3.884427547454834, 0.75]
1/1 [==============================] - 0s 115ms/step - loss: 1.1469 - accuracy: 0.7500
Activation: elu - Optimizer: rmsprop - Loss: mean_squared_error - Metric: accuracy
S